### ISSUE TITLE
Dockerfile feedback

### ISSUE THREAD

**Issue by BretFisher** [shaun-lloyd/ardupilot-docker#1]
A few recommendations

1. The main purpose of creating a standard user in a Dockerfile, usually, is to prevent the app from having access to container-root. Giving that 1000 user sudo negates that benefit. I'm assuming the steps taken are to ensure the GitHub clone files have the proper permissions... so unless the apps require it, I would either skip the normal user account thing altogether, leaving everything as the default container-root, which will greatly simplify the Dockerfile and permissions issues (and potential permission issues when bind-mounting in Docker Desktop for development), *or*, for cases where this is running "in production" I would remove the sudoers file at the end of the Dockerfile to limit the user permissions.
1. Don't use sudo in Dockerfiles, per the [best practices](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#user). Try using [gosu instead](https://github.com/tianon/gosu).
1. [This cleanup does nothing](https://github.com/shaun-lloyd/ardupilot-docker/blob/76864b76e621ff0ad01d2b6801725e882811e223/Dockerfile#L48-L50) unless it's combined in the same RUN command that did the apt-get update/install.  Move it to the end of lines 12-14 and also 40 to ensure caches are not added to previous layers.
1. Add `--depth 1` to options of both `git clone` and `git submodule update` to save time and space.
1. Consider ubuntu:20.04 as FROM image.
1. Even if you're not changing the CMD, it's best to repeat it on the last Dockerfile line of a output stage so people looking at your build understand what it will do on startup of that stage.
1. Add better docs in Dockerfile and README for describing the reasons to use the different stages, and which ones are used in which images on docker hub.
1. Consider pinning your hub images to upstream [ArduPilot releases](https://github.com/ArduPilot/ardupilot/releases).

Following steps 2 and 4 above I shaved 420MB and 4 seconds on fresh build without cache 👍 

Overall good job!

**Comment by shaun-lloyd** [comment]
1. Actually is the "app", the python "environment" requires the account. But i take your points on board and shall investigate, it certainly "feels" like a hack.

2. Done.
3. Done.
4. Done.

5. This is as ardupilot suggest, Shall add testing-20.04 build target, start doing some testing. Love multistage builds !

6. Done.
7. Done. But i'll do better.

8. Check. I wanted to have full "supported" os list including upstream. Trying to keep "simple". Will FIX.

Funny hadn't really considered build time, except for APT_CACHE but that's docker wide. Thanks for that !

Your too kind, i suck. But thanks for saying. When it's accepted upstream then it's good job.
